### ISSUE TITLE
`flow check-contents` causes funny errors

### ISSUE THREAD

**Issue by LPGhatguy** [SublimeLinter/SublimeLinter-flow#47] opened 2016-12-16 20:08 UTC
Flow reports errors differently between `flow` and `flow check-contents` in some specific cases! I've started seeing ghost errors reported from SublimeLinter-flow because of it. See facebook/flow#2235 for the upstream issue.

Are there any options available to allow SublimeLinter-flow to work around this? One comment on the linked issue mentions a proposal for better IDE integration. One other comment mentioned that there's an IDE that uses `flow` for files that have been saved and `flow check-contents` for unsaved files.

**Comment by davidaurelio** [comment] 2016-12-31 09:59
`check-contents` also does not report “unused suppression” errors. 

I hope it can be fixed upstream. Using `check` and `check-contents` depending on whether a buffer is saved, and getting different results, might feel very weird.

**Comment by braver** [comment] 2018-05-17 13:53
duplicate of #50

**Closed by braver** 2018-05-17 13:53 UTC
Labels: question
